name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install shut==0.17.2 -q
    - name: Test
      run: shut pkg test --isolate
    - name: Verify package metadata
      run: shut update --verify
